services:
  prueba-tecnica-db:
    container_name: prueba-tecnica-db
    restart: always
    image: postgres:16.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5890:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prueba-tecnica

  prueba-tecnica-redis:
    container_name: prueba-tecnica-redis
    restart: always
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes: 
  pgdata:
  redisdata: