name: Verify Backend Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  verify-build:
    name: Verify Backend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to backend and setup
        run: |
          cd backend
          npm ci
          npm run build
